import './admin-user';
import './profile-edit-profile';
import './profile-edit-password';
import './pessoa';
import './endereco';
import './p-fisica';
import './p-juridica';
import './veiculo';
import './plano';
